version: "3.3"

services:
  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    image: ddubson/config-server:1.0
    ports:
      - "8889:8889"

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: ddubson/app:1.0
    depends_on:
      - config-server
    environment:
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8889"
    ports:
      - "8080:8080"

